
SELECT distinct (i.IMPRESSIONID) , i. ADVERTISERID ,i.APPID , i.COUNTRYCODE, count(i.IMPRESSIONID),sum(c.REVENUE) , cc.clicks  FROM IMPRESSIONS i  inner join CLICKS c on i.IMPRESSIONID   =  c.IMPRESSIONID join (select IMPRESSIONID , count(*) clicks from CLICKS group by IMPRESSIONID)  cc on c.IMPRESSIONID   =  cc.IMPRESSIONID  group by i.IMPRESSIONID, i. ADVERTISERID ,i.APPID , i.COUNTRYCODE;

SELECT distinct(i.ADVERTISERID), i.IMPRESSIONID  ,i. APPID , i.COUNTRYCODE, c.REVENUE   FROM IMPRESSIONS i  inner join CLICKS c on i.IMPRESSIONID = c.IMPRESSIONID order by  APPID , COUNTRYCODE, c.REVENUE ;

SELECT distinct(i.ADVERTISERID), i.IMPRESSIONID  ,i. APPID , i.COUNTRYCODE   FROM IMPRESSIONS i  order by  APPID , COUNTRYCODE ;

SELECT distinct(i.ADVERTISERID), i.IMPRESSIONID  ,i. APPID , i.COUNTRYCODE, c.REVENUE    FROM IMPRESSIONS i  inner join CLICKS c on i.IMPRESSIONID = c.IMPRESSIONID  order by  i.APPID , i.COUNTRYCODE ;

SELECT distinct(i.ADVERTISERID), i.IMPRESSIONID  ,i. APPID , i.COUNTRYCODE, c.REVENUE    FROM IMPRESSIONS i  left  join CLICKS c on i.IMPRESSIONID = c.IMPRESSIONID  order by  i.APPID , i.COUNTRYCODE ;